title: ""
description: ""
baseurl: ""
url: ""

copyright: false
indexing: false

exclude:
  - demo/
  - jekyll-nagymaros.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
